catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set vpp_optimize_level 0
open_project mm
set_top mm
add_files "/ihome/ageorge/mah473/Desktop/Vitis_Accel_Examples/lab5_test_v4/src/mm.cpp" -cflags " -I /ihome/ageorge/mah473/Desktop/Vitis_Accel_Examples/lab5_test_v4/src "
open_solution solution
set_part xcu200-fsgd2104-2-e
create_clock -period 300.000000MHz -name default
config_sdx -target xocc
config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_rtl -enable_maxiConservative=1
config_interface -m_axi_addr64
config_export -format ip_catalog -ipname mm
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
